"""empty message

Revision ID: 92218fb161f9
Revises: 
Create Date: 2025-09-12 00:59:17.204775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92218fb161f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('room',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('in_3d', sa.Boolean(), nullable=False),
    sa.Column('device', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    op.drop_table('user')
    # ### end Alembic commands ###
