"""empty message

Revision ID: e3a5a43768a4
Revises: 92218fb161f9
Create Date: 2025-10-02 13:49:20.682635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a5a43768a4'
down_revision = '92218fb161f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=False),
    sa.Column('in_3d', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('room')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('owner', sa.VARCHAR(length=36), nullable=False),
    sa.Column('in_3d', sa.BOOLEAN(), nullable=False),
    sa.Column('device', sa.VARCHAR(length=80), nullable=True),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('device')
    # ### end Alembic commands ###
