name: Backend CI

on:
  push:
    paths:
      - 'backend/**'
      - 'pyproject.toml'
      - '.github/workflows/backend-ci.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'pyproject.toml'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Ruff
        run: |
          source .venv/bin/activate
          ruff check backend/app tests
      - name: Mypy
        run: |
          source .venv/bin/activate
          mypy backend/app || true
      - name: Pytest
        run: |
          source .venv/bin/activate
          pytest --cov=backend/app --cov-report=term-missing